name: Show Branch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name 1
        run: echo running show-branch.yml from test branch.
      - name: Branch name 2
        run: echo running on branch ${GITHUB_REF##*/}
      # - name: Build
      #   run: docker build -t tedmiston/tag-example:${GITHUB_REF##*/} .
