name: Github Actions Test

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Set tag var
      id: vars
      run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}
    - name: Print tag var
      run: echo "${{ steps.vars.outputs.docker_tag }}"
    - name: Get git tag
      id: set_git_vars
      run: echo ::set-output name=GIT_TAG::$(git tag --points-at HEAD)
    - name: Print git tag
      run: |
        echo "${{ steps.set_git_vars.outputs.GIT_TAG }}"
    
    #- name: Dump GitHub context
    #  env:
    #    GITHUB_CONTEXT: ${{ toJson(github) }}
    #  run: echo "$GITHUB_CONTEXT" 
    - name: step hello
      run: |
        echo hello world!
        
    - name: create artifacts
      run: echo artifacts
      if: github.event_name == 'push' && ( github.ref == 'refs/heads/master' || github.ref == 'refs/heads/devel' )
